Repository babylonchain/simple-staking, pull requests merged in 2024-05, with the labels that each got.

#86 feat/35 graceful error handling
  src/app/api/getStakers.ts
  src/app/components/Delegations/Delegations.tsx
  src/app/components/Modals/ErrorModal.tsx
  src/app/components/Stakers/Stakers.tsx
  src/app/components/Staking/Staking.tsx
  src/app/context/Error/ErrorContext.tsx
  src/app/page.tsx
  src/app/providers.tsx
  src/app/types/errors.ts
Labels: enhancement

#135 add new message for current block height vs activation block height
  src/app/components/Delegations/Delegations.tsx
  src/app/components/Staking/Staking.tsx
  src/app/page.tsx
Labels: high

#150 fix: Activate the form one height prior the activation height
  src/app/components/Staking/Staking.tsx
  src/app/page.tsx
Labels: bug

#152 fix: confusing states display
  src/app/components/Delegations/Delegations.tsx
  src/app/components/Modals/ErrorModal.tsx
  src/app/types/errors.ts
  src/utils/getState.ts
Labels: bug

#158 remove loader on empty list
  src/app/components/Delegations/Delegations.tsx
  src/app/components/Staking/Form/StakingAmount.tsx
Labels: high

#180 fix - inception time refesh
  src/app/components/Delegations/Delegation.tsx
  src/utils/formatTime.ts
Labels: bug

#173 fix first activation height
  src/app/components/Delegations/Delegations.tsx
  src/app/components/Staking/Staking.tsx
  src/app/page.tsx
  src/utils/globalParams.ts
Labels: bug

#206 fix modal freeze after open
  src/app/components/Modals/GeneralModal.tsx
Labels: bug
